CREATE TABLE Paquete(
	Codigo NVARCHAR(20),
	Direccion NVARCHAR(100) NOT NULL,
	Destinatario NVARCHAR(100) NOT NULL,
	Peso INT,
	CONSTRAINT PK_Paquete PRIMARY KEY(Codigo)
);

CREATE TABLE Conductor(
	RFC NVARCHAR(13),
	Nombre NVARCHAR(50) NOT NULL,
	Direccion NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Conductor PRIMARY KEY(RFC)
);

CREATE TABLE Rutas_Conductor(
	RFC NVARCHAR(13),
	Ruta NVARCHAR(100) NOT NULL,
	CONSTRAINT FK_Rut_Cond FOREIGN KEY(RFC)
	REFERENCES Conductor(RFC) ON DELETE CASCADE
);

CREATE TABLE Camion(
	Placa NVARCHAR(6),
	CargaMaxima INT NOT NULL,
	CiudadResguardo NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Camion PRIMARY KEY(Placa)
);

CREATE TABLE Conductor_Camion(
	RFC NVARCHAR(13),
	Placa NVARCHAR(6),
	Fecha DATE,
	CONSTRAINT PK_Conductor_Camion PRIMARY KEY(RFC, Placa),
	CONSTRAINT FK_RFC FOREIGN KEY(RFC)
	REFERENCES Conductor(RFC) ON DELETE CASCADE,
	CONSTRAINT FK_Placa FOREIGN KEY(Placa)
	REFERENCES Camion(Placa) ON DELETE CASCADE
);

CREATE TABLE Nacional(
	Codigo NVARCHAR(20),
	RFC NVARCHAR(13),
	Ciudad NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Nacional PRIMARY KEY(Codigo),
	CONSTRAINT FK_Paq_Nac FOREIGN KEY(Codigo)
	REFERENCES Paquete(Codigo) ON DELETE CASCADE,
	CONSTRAINT FK_Nac_Con FOREIGN KEY(RFC)
	REFERENCES Conductor(RFC) ON DELETE CASCADE 
);

CREATE TABLE Rutas_Nacional(
	Codigo NVARCHAR(20),
	Ruta NVARCHAR(100) NOT NULL,
	CONSTRAINT FK_Rut_Nac FOREIGN KEY(Codigo)
	REFERENCES Nacional(Codigo) ON DELETE CASCADE
);

CREATE TABLE C_Local(
	CodigoLocal NVARCHAR(20),
	Nombre NVARCHAR(30) NOT NULL,
	CONSTRAINT PK_C_Local PRIMARY KEY(CodigoLocal)
);

CREATE TABLE Internacional(
	Codigo NVARCHAR(20),
	CodigoLocal NVARCHAR(20),
	LineaAerea NVARCHAR(30) NOT NULL,
	FechaEntrega DATE NOT NULL,
	CONSTRAINT PK_Internacional PRIMARY KEY(Codigo),
	CONSTRAINT FK_Paq_Int FOREIGN KEY(Codigo)
	REFERENCES Paquete(Codigo) ON DELETE CASCADE,
	CONSTRAINT FK_Int_Local FOREIGN KEY(CodigoLocal)
	REFERENCES C_Local(CodigoLocal) ON DELETE CASCADE
);

ALTER TABLE Rutas_Conductor DROP CONSTRAINT FK_Rut_Cond;
ALTER TABLE Conductor_Camion DROP CONSTRAINT FK_RFC;
ALTER TABLE Conductor_Camion DROP CONSTRAINT FK_Placa;
ALTER TABLE Rutas_Nacional DROP CONSTRAINT FK_Rut_Nac;
ALTER TABLE Nacional DROP CONSTRAINT FK_Paq_Nac;
ALTER TABLE Nacional DROP CONSTRAINT FK_Nac_Con;
ALTER TABLE Internacional DROP CONSTRAINT FK_Paq_Int;
ALTER TABLE Internacional DROP CONSTRAINT FK_Int_Local;

DROP TABLE Paquete;
DROP TABLE Conductor;
DROP TABLE Rutas_Conductor;
DROP TABLE Camion;
DROP TABLE Conductor_Camion;
DROP TABLE Nacional;
DROP TABLE Rutas_Nacional;
DROP TABLE C_Local;
DROP TABLE Internacional;